server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

  messages:
    basename: lang.messages

  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/

  liquibase:
    enabled: true
    default-schema: com_example



